version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_container
    ports:
      - "80:80"
    restart: always
    depends_on:
    - spring
    networks: 
      - spring-network

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@2001
      MYSQL_DATABASE: user
    
    restart: always
    volumes:
      - spring-app-data:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pMysql@2001"]
      retries: 5
      interval: 10s
      timeout: 5s
      start_period: 60s

  spring:
    # build:
      # context: .
    image: nithu02/spring-app
    container_name: spring
    ports:  
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/user?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_PASSWORD: Mysql@2001
    restart: always
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
      
networks:
  spring-network:
volumes:
  spring-app-data:
